document.addEventListener('DOMContentLoaded',async()=>{
  const grid=document.querySelector('#featuredGrid');
  try{
    const products=await Punto.api('/products');
    grid.innerHTML=products.slice(0,8).map(product=>`<article class="product-card"><div class="product-media"><a href="/producto/${product.id}"><img loading="lazy" src="${Punto.esc(product.img)}" alt="${Punto.esc(product.name)}"></a><span class="product-tag">${Punto.esc(product.tag||'NUEVO')}</span><button class="favorite ${Punto.favorites().includes(Number(product.id))?'active':''}" type="button" data-favorite="${product.id}" aria-label="Guardar ${Punto.esc(product.name)}" aria-pressed="${Punto.favorites().includes(Number(product.id))}">${Punto.favorites().includes(Number(product.id))?'♥':'♡'}</button><button class="quick-add" type="button" data-home-add="${product.id}">＋ AGREGAR TALLA ${Punto.esc(product.variants.find(v=>v.stock>0)?.size||'')}</button></div><div class="product-info-card"><small>${Punto.esc(product.category)} · ${Punto.esc(product.color)}</small><h3><a href="/producto/${product.id}">${Punto.esc(product.name)}</a></h3><div class="product-meta"><strong>${Punto.money(product.price)} COP</strong><span>${product.stock} DISPONIBLES</span></div></div></article>`).join('');
    grid.addEventListener('click',event=>{const button=event.target.closest('[data-home-add]');if(!button)return;const product=products.find(p=>p.id===Number(button.dataset.homeAdd)),variant=product?.variants.find(v=>v.stock>0);if(product&&variant)Punto.add(product,variant.size)});
  }catch(error){grid.innerHTML=`<div class="empty-state"><h2>No pudimos cargar el catálogo</h2><p>${Punto.esc(error.message)}</p></div>`}
  const quote=document.querySelector('#quoteForm');quote.addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(quote));try{await Punto.api('/quotes',{method:'POST',body:JSON.stringify(values)});quote.reset();Punto.toast('Solicitud recibida. Te contactaremos para continuar.')}catch(error){Punto.toast(error.message)}});
});
