(function(){
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const money=n=>'$'+Number(n||0).toLocaleString('es-CO');
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  async function api(path,options={}){const response=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},credentials:'same-origin',...options});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||'No fue posible completar la operación');return data}
  let cart=[];try{cart=JSON.parse(localStorage.getItem('pintao-cart')||localStorage.getItem('punto1-cart')||'[]')}catch{cart=[]}
  let favorites=[];try{favorites=JSON.parse(localStorage.getItem('pintao-favorites')||localStorage.getItem('punto1-favorites')||'[]')}catch{favorites=[]}
  let settings={freeShipping:250000,minOrder:6,whatsapp:''};
  const totals=()=>{const count=cart.reduce((s,x)=>s+Number(x.qty||0),0),base=cart.reduce((s,x)=>s+Number(x.price||0)*Number(x.qty||0),0),rate=count>=48?.25:count>=24?.18:count>=12?.10:0;return {count,base,rate,total:Math.round(base*(1-rate))}};
  function saveCart(){localStorage.setItem('pintao-cart',JSON.stringify(cart));renderCart();document.dispatchEvent(new CustomEvent('pintao:cart'))}
  function add(product,size,qty=1){const variant=product.variants?.find(v=>v.size===size),available=variant?.stock??product.stock??0;if(!available)return toast('Esta talla no tiene inventario');const existing=cart.find(x=>Number(x.id)===Number(product.id)&&x.size===size);if(existing)existing.qty=Math.min(available,existing.qty+qty);else cart.push({id:product.id,name:product.name,price:product.price,img:product.img,size,qty:Math.min(available,qty),stock:available});saveCart();openCart();toast('Producto agregado al carrito')}
  function toggleFavorite(id){id=Number(id);favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('pintao-favorites',JSON.stringify(favorites));$$(`[data-favorite="${id}"]`).forEach(button=>{button.classList.toggle('active',favorites.includes(id));button.textContent=favorites.includes(id)?'♥':'♡';button.setAttribute('aria-pressed',String(favorites.includes(id)))})}
  function toast(message){let node=$('#siteToast');if(!node){node=document.createElement('div');node.id='siteToast';node.className='toast';node.setAttribute('role','status');document.body.append(node)}node.textContent=message;node.classList.add('show');clearTimeout(node.timer);node.timer=setTimeout(()=>node.classList.remove('show'),2600)}
  function injectChrome(){if(!$('#cartDrawer'))document.body.insertAdjacentHTML('beforeend',`<div class="cart-overlay" id="cartOverlay"></div><aside class="cart-drawer" id="cartDrawer" role="dialog" aria-modal="true" aria-labelledby="cartTitle" aria-hidden="true"><button class="drawer-close" type="button" data-cart-close aria-label="Cerrar carrito">×</button><span class="eyebrow">TU PINTA</span><h2 id="cartTitle">Tu carrito</h2><div class="shipping-progress"><span id="shippingText">Agrega productos para obtener envío gratis</span><i><b id="shippingBar"></b></i></div><div class="cart-items" id="cartItems"></div><div class="cart-summary"><div><span>Subtotal estimado</span><strong id="cartTotal">$0</strong></div><small id="cartDiscount">Los descuentos por volumen se aplican automáticamente.</small><a class="button dark full" href="/checkout">FINALIZAR PEDIDO</a></div></aside>`)}
  function renderCart(){const total=totals();$$('[data-cart-count]').forEach(node=>node.textContent=total.count);const items=$('#cartItems');if(!items)return;items.innerHTML=cart.length?cart.map((item,index)=>`<article class="cart-item"><img src="${esc(item.img)}" alt="${esc(item.name)}"><div><strong>${esc(item.name)}</strong><span>Talla ${esc(item.size)} · ${money(item.price)}</span><div class="cart-controls"><button type="button" data-cart-dec="${index}" aria-label="Restar unidad">−</button><b>${item.qty}</b><button type="button" data-cart-inc="${index}" aria-label="Sumar unidad">+</button><button type="button" class="cart-remove" data-cart-remove="${index}">ELIMINAR</button></div></div><strong>${money(item.price*item.qty)}</strong></article>`).join(''):'<div class="cart-empty">Tu carrito está vacío.<br>Explora el catálogo y elige tus referencias.</div>';$('#cartTotal').textContent=money(total.total);const goal=Number(settings.freeShipping||250000),pct=Math.min(100,total.total/goal*100);$('#shippingBar').style.width=pct+'%';$('#shippingText').textContent=total.total>=goal?'Tu pedido alcanza el beneficio de envío gratis':`Te faltan ${money(Math.max(0,goal-total.total))} para envío gratis`;$('#cartDiscount').textContent=total.rate?`Descuento mayorista aplicado: ${Math.round(total.rate*100)}%. El envío se confirma antes del pago.`:'Los descuentos por volumen se aplican desde 12 unidades.'}
  function openCart(){const drawer=$('#cartDrawer'),overlay=$('#cartOverlay');if(!drawer)return;drawer.classList.add('open');overlay.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('drawer-open');drawer.querySelector('[data-cart-close]').focus()}
  function closeCart(){const drawer=$('#cartDrawer'),overlay=$('#cartOverlay');if(!drawer)return;drawer.classList.remove('open');overlay.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('drawer-open')}
  async function loadSettings(){try{settings=await api('/settings');renderCart();$$('[data-min-order]').forEach(x=>x.textContent=settings.minOrder);$$('[data-free-shipping]').forEach(x=>x.textContent=money(settings.freeShipping));$$('[data-whatsapp]').forEach(link=>{if(settings.whatsapp){link.href=`https://wa.me/${settings.whatsapp}`;link.hidden=false}else{link.hidden=true}})}catch{renderCart()}}
  function bind(){injectChrome();renderCart();loadSettings();document.addEventListener('click',event=>{const target=event.target.closest('[data-cart-open],[data-cart-close],[data-cart-inc],[data-cart-dec],[data-cart-remove],[data-favorite],[data-search-open],[data-search-close],[data-menu]');if(!target)return;if(target.matches('[data-cart-open]'))openCart();if(target.matches('[data-cart-close]'))closeCart();if(target.matches('[data-cart-inc]')){const item=cart[Number(target.dataset.cartInc)];item.qty=Math.min(item.stock||99,item.qty+1);saveCart()}if(target.matches('[data-cart-dec]')){const i=Number(target.dataset.cartDec);cart[i].qty--;if(cart[i].qty<1)cart.splice(i,1);saveCart()}if(target.matches('[data-cart-remove]')){cart.splice(Number(target.dataset.cartRemove),1);saveCart()}if(target.matches('[data-favorite]'))toggleFavorite(target.dataset.favorite);if(target.matches('[data-search-open]')){$('#searchStrip')?.classList.add('open');setTimeout(()=>$('#globalSearch')?.focus(),100)}if(target.matches('[data-search-close]'))$('#searchStrip')?.classList.remove('open');if(target.matches('[data-menu]'))$('#mainNav')?.classList.toggle('open')});$('#cartOverlay')?.addEventListener('click',closeCart);document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeCart();$('#searchStrip')?.classList.remove('open')}});$('#globalSearchForm')?.addEventListener('submit',event=>{event.preventDefault();const q=$('#globalSearch').value.trim();location.href='/catalogo'+(q?'?q='+encodeURIComponent(q):'')});const newsletter=$('#newsletterForm');newsletter?.addEventListener('submit',async event=>{event.preventDefault();const email=new FormData(newsletter).get('email');try{await api('/newsletter',{method:'POST',body:JSON.stringify({email})});newsletter.reset();toast('Correo registrado. Te avisaremos de los próximos ingresos.')}catch(error){toast(error.message)}});if(!localStorage.getItem('pintao-cookie-choice')&&!localStorage.getItem('punto1-cookie-choice')&&!$('#cookieNotice'))document.body.insertAdjacentHTML('beforeend','<div class="cookies" id="cookieNotice"><p>Usamos almacenamiento local para recordar tu carrito y preferencias.</p><div><button type="button" data-cookie="reject">RECHAZAR</button><button type="button" class="accept" data-cookie="accept">ACEPTAR</button></div></div>');$$('[data-cookie]').forEach(button=>button.onclick=()=>{localStorage.setItem('pintao-cookie-choice',button.dataset.cookie);$('#cookieNotice')?.remove()})}
  function addCanonical(){if(document.querySelector('link[rel="canonical"]'))return;const link=document.createElement('link');link.rel='canonical';link.href=location.origin+location.pathname;document.head.append(link)}
  function protectBrandTitle(){const title=document.querySelector('title');if(!title)return;const sync=()=>{if(document.title.includes('Punto Uno'))document.title=document.title.replaceAll('Punto Uno','PINTAO')};sync();new MutationObserver(sync).observe(title,{childList:true,characterData:true,subtree:true})}
  document.addEventListener('DOMContentLoaded',()=>{protectBrandTitle();addCanonical();bind()});
  window.Punto={api,money,esc,add,cart:()=>cart,favorites:()=>favorites,toggleFavorite,toast,settings:()=>settings,renderCart,saveCart,totals};
})();
